CREATE TABLE IF NOT EXISTS players (team string, num integer, role string, firstname string, lastname string, unique(num, team))
CREATE TABLE IF NOT EXISTS teams (team string, unique(team))
CREATE TABLE IF NOT EXISTS games (time string, venue string, ot boolean, winner string, loser string, ref_name string, ref_lname string, unique(time, venue))
CREATE TABLE IF NOT EXISTS goals (game_time string, venue string, team string, s integer, time string, p1 integer, p2 integer, p3 integer, other string, unique(game_time, venue, time))
CREATE TABLE IF NOT EXISTS penalties (game_time string, venue string, time string, team string, player integer, ref_name string, ref_lname string, unique(game_time, venue, time))
CREATE TABLE IF NOT EXISTS referees (firstname string, lastname string, unique(firstname, lastname))